model: YTDNN
seed: 2020
Double_Tower: True
encoder_type: ~
use_modality: False
checkpoint_dir: YTDNN/saved
MAX_ITEM_LIST_LENGTH: 20

embedding_size: 2048
dropout_prob: 0
mlp_hidden_size: []


data_path: ../data
dataset: bisc
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id


# Training and evaluation config


metric_decimal_place: 7


# Training and evaluation config
epochs: 220

train_batch_size: 256  #2500     4卡：16,单卡：64
eval_batch_size: 1280

learning_rate: 0.0005
weight_decay: 0

neg_sampling_num: 1
neg_sampling: {'uniform' : 1}

eval_step: 1 #每次训练后做evalaution的次数
stopping_step: 30


topk: [5,10]
metrics: ['Recall', 'NDCG']
valid_metric: NDCG@10
metric_decimal_place: 7

